# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"core_test": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hallmx.github.io/fa_convnav/"

git_url = "https://github.com/hallmx/fa_convnav/tree/master/"

def custom_doc_links(name): return None
