# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"find_model": "00_core.ipynb",
         "get_row": "00_core.ipynb",
         "get_inp_sz": "00_core.ipynb",
         "infos_to_gen": "00_core.ipynb",
         "CNDF": "00_core.ipynb",
         "cndf_view": "01_navigator.ipynb",
         "add_container_row_info": "01_navigator.ipynb",
         "cndf_search": "01_navigator.ipynb",
         "ConvNav": "01_navigator.ipynb",
         "cndf_save": "01_navigator.ipynb",
         "cndf_load": "01_navigator.ipynb",
         "vgg": "02_models.ipynb",
         "alexnet": "02_models.ipynb",
         "squeezenet": "02_models.ipynb",
         "resnet": "02_models.ipynb",
         "densenet": "02_models.ipynb",
         "xresnet": "02_models.ipynb",
         "models": "02_models.ipynb",
         "pets": "03_examples00.ipynb",
         "dls": "03_examples00.ipynb",
         "dls.show_batch(max_n": "03_examples00.ipynb",
         "model": "03_examples00.ipynb",
         "learn": "03_examples00.ipynb",
         "cn": "03_examples00.ipynb",
         "cn.view(top": "03_examples00.ipynb",
         "layers": "03_examples00.ipynb"}

modules = ["core.py",
           "navigator.py",
           "models.py",
           "examples00.py"]

doc_url = "https://hallmx.github.io/fa_convnav/"

git_url = "https://github.com/hallmx/fa_convnav/tree/master/"

def custom_doc_links(name): return None
