# AUTOGENERATED! DO NOT EDIT! File to edit: 01_navigator.ipynb (unless otherwise specified).

__all__ = ['Convnav', 'navigator_test']

# Cell
import fastai2
from .models import *

# Cell

class Convnav:
  "CNN navigator. Creates a dataframe of model layers and methods to view/select layers and modules"

  def __init__(self, learner):
     self.learner = learner
     self.model = learner.model
     self.layers = list(learner.model.named_modules())
     self.num_layers = len(self.layers)
     self.model_type, self.model_name = find_model(self.num_layers)

  def supported_models(self):
    "Print a list of supported models"
    supported_models(models)











# Cell
def navigator_test(test):
  "Navigator"
  print(test)